export const FETCHCAMPAIGN = 'FETCHCAMPAIGN';
export const GETCAMPAIGN = 'GETCAMPAIGN';
export const CREATECAMPAIGN = 'CREATECAMPAIGN';
export const UPDATECAMPAIGN = 'UPDATECAMPAIGN';
export const DELETECAMPAIGN = 'DELETECAMPAIGN';
export const FILTERCAMPAIGN = 'FILTERCAMPAIGN';