export const FETCHSEGMENT = 'FETCHSEGMENT';
export const GETSEGMENT = 'GETSEGMENT';
export const CREATESEGMENT = 'CREATESEGMENT';
export const UPDATESEGMENT = 'UPDATESEGMENT';
export const DELETESEGMENT = 'DELETESEGMENT';
export const FILTERSEGMENT = 'FILTERSEGMENT';